version: "3"

services:
  albert_gazebo:
    image: krr:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    command: stdbuf -o L roslaunch albert_gazebo albert_gazebo_navigation.launch world:=AH_store 
    restart: always
