waypoints:
  wp0:
    position:
      x: -0.3
      y: -0.5
      z: 0.0
    yaw: 0.0
  wp1:
    position:
      x: -0.3
      y: -0.5
      z: 0.0
    yaw: 0.0
  wp2:
    position:
      x: -0.3
      y: -0.5
      z: 0.0
    yaw: 0.0
  wp3:
    position:
      x: -0.3
      y: -0.5
      z: 0.0
    yaw: 0.0
  wp4:
    position:
      x: -0.3
      y: -0.5
      z: 0.0
    yaw: 0.0

