waypoints:
  wp0:
    x: -0.3
    y: -0.5
    z: 0.0
    yaw: 0.0
  wp1:
    x: -0.3
    y: -0.5
    z: 0.0
    yaw: 0.0
  wp2:
    x: -0.3
    y: -0.5
    z: 0.0
    yaw: 0.0
  wp3:
    x: -0.3
    y: -0.5
    z: 0.0
    yaw: 0.0
  wp4:
    x: -0.3
    y: -0.5
    z: 0.0
    yaw: 0.0
  wp5:
    x: -0.3
    y: -0.5
    z: 0.0
    yaw: 0.0
  
