waypoints:
  wp0:
    x: 0.90
    y: -0.131
    z: 0.0
    yaw: 0.0
  wp1:
    x: 2.05
    y: 0.95
    z: 0.0
    yaw: 1.57
  wp2:
    x: 3.91
    y: 0.95
    z: 0.0
    yaw: 1.57
  wp3:
    x: 3.97
    y: 1.25
    z: 0.0
    yaw: -1.57
  wp4:
    x: 4.16
    y: -1.8
    z: 0.0
    yaw: 1.57
  wp5:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  
