waypoints:
  wp0:
    x: -2.0
    y: -1.5
    z: 0.0
    yaw: 3.14
  wp1:
    x: -2.0
    y: -0.5
    z: 0.0
    yaw: 3.14
  wp2:
    x: -2.0
    y: 0.5
    z: 0.0
    yaw: 3.14
  wp3:
    x: -2.0
    y: 1.5
    z: 0.0
    yaw: 3.14
  wp4:
    x: 1
    y: 3
    z: 0.0
    yaw: 1.57
  wp5:
    x: -1
    y: 4
    z: 0.0
    yaw: 1.57
  
